In [780]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

# Viterbi

In [782]:
# From "https://stackoverflow.com/questions/9729968/python-implementation-of-viterbi-algorithm"
def viterbi(y, A, B, Pi=None):
    """
    Return the MAP estimate of state trajectory of Hidden Markov Model.

    Parameters
    ----------
    y : array (T,)
        Observation state sequence. int dtype.
    A : array (K, K)
        State transition matrix. See HiddenMarkovModel.state_transition  for
        details.
    B : array (K, M)
        Emission matrix. See HiddenMarkovModel.emission for details.
    Pi: optional, (K,)
        Initial state probabilities: Pi[i] is the probability x[0] == i. If
        None, uniform initial distribution is assumed (Pi[:] == 1/K).

    Returns
    -------
    x : array (T,)
        Maximum a posteriori probability estimate of hidden state trajectory,
        conditioned on observation sequence y under the model parameters A, B,
        Pi.
    T1: array (K, T)
        the probability of the most likely path so far
    T2: array (K, T)
        the x_j-1 of the most likely path so far
    """
    
    # Cardinality of the state space
    K = A.shape[0]
    # Initialize the priors with default (uniform dist) if not given by caller
    Pi = Pi if Pi is not None else np.full(K, 1 / K)
    T = len(y)
    T1 = np.empty((K, T), 'd')
    T2 = np.empty((K, T), 'B')

    # Initialize the tracking tables from first observation
    T1[:, 0] = np.log(Pi * B[:, y[0]])
    T2[:, 0] = 0

    # Iterate through the observations updating the tracking tables
    for i in range(1, T):
        #need to subtract 1 from y as it ranges from 1-6 but indexed 0 in array
        T1[:, i] = np.max(T1[:, i - 1] + np.log(A), 1) + np.log(B[np.newaxis, :, y[i] - 1])
        T2[:, i] = np.argmax(T1[:, i - 1] + np.log(A), 1)

    # Build the output, optimal model trajectory
    x = np.empty(T, 'B')
    x[-1] = np.argmax(T1[:, T - 1])
    #flip since we are backtracking
    for i in reversed(range(1, T)):
        x[i - 1] = T2[x[i], i]

    return x, T1, T2

In [783]:
obs_a = np.loadtxt("../datasets/markov/hmm_pb1.csv", dtype = int, delimiter = ",")
obs_a_pd = pd.read_csv("../datasets/markov/hmm_pb1.csv", header=None)
pi_a = np.array([0.5, 0.5])
trans_a = np.array([
                    [0.95, 0.05],
                    [0.05, 0.95]
                   ])
emit_a = np.array([
                    [1/6, 1/6, 1/6, 1/6, 1/6, 1/6],
                    [1/10, 1/10, 1/10, 1/10, 1/10, 1/2]
                  ])

In [1186]:
y, T1, T2 = viterbi(obs_a, trans_a, emit_a, pi_a)

In [1188]:
#y = 1 is Fair, y=2 is loaded
print(y+1)
print(T1)
print(T2)

[1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1
 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1
 1 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2
 2 2 2 2 2 2 2 2 2 2 2 2 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1
 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1
 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2
 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2
 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2]
[[  -2.48490665   -4.32795941   -6.17101218   -8.01406494   -9.8571177
   -11.70017047  -13.54322323  -15.386276    -17.22932876  -19.07238152
   -20.91543429  -22.75848705  -24.60153981  -26.44459258  -28.28764534
   -30.1306981   -31.97375087  -33.81680363  -35.65985639  -37.50290916
   -39.34596192  -41.18901469  -43.03206745  -44.87512021  -46.71817298
   -48.56122574  -50.4042785   -52.24733127  -54.09038403  -55.93343679
   -57.776

# Forward Algorithm

In [1216]:
#Modified from "http://www.adeveloperdiary.com/data-science/machine-learning/forward-and-backward-algorithm-in-hidden-markov-model/"
def forward(observations, transition_matrix, emission_matrix, pi):
    #python indexed 0 so subtract 1 from all dice rolls
    observations = observations - 1
    #get number of observations
    observations_rows = observations.shape[0]
    #get number of states (K)
    K = transition_matrix.shape[0]
    
    #Initialize alpha probabilities
    alpha = np.zeros([observations_rows, K])
    alpha[0, :] = pi * emission_matrix[:, observations[0]]
    alpha_probs = np.zeros([observations_rows, K])
    alpha_probs[0] = alpha[0] / np.sum(alpha[0])
    
    #common factor to avoid underflow
    #u = np.zeros([observations_rows - 1, K])
    
    #iterate forward through observations to compute alpha probabilities
    for t, obs in enumerate(observations[1:], 1):
            alpha[t] = np.array([
                            #start with probability we go from previous state to fair
                            emission_matrix[0][obs] * np.sum([
                                #chance from fair to fair
                                alpha[t - 1][0] * transition_matrix[0, 0],
                                #chance from loaded to fair
                                alpha[t - 1][1] * transition_matrix[1, 0]
                                ]),
                            #go from previous state to loaded
                            emission_matrix[1][obs] * np.sum([
                                #chance from fair to loaded
                                alpha[t - 1][0] * transition_matrix[0, 1],
                                #chance from loaded to loaded
                                alpha[t - 1][0] * transition_matrix[1, 1]
                                ]),
                            ])
            alpha_probs[t] = np.array([
                            #start with probability we go from previous state to fair
                            emission_matrix[0][obs] * np.sum([
                                #chance from fair to fair
                                alpha_probs[t - 1][0] * transition_matrix[0, 0],
                                #chance from loaded to fair
                                alpha_probs[t - 1][1] * transition_matrix[1, 0]
                                ]),
                            #go from previous state to loaded
                            emission_matrix[1][obs] * np.sum([
                                #chance from fair to loaded
                                alpha_probs[t - 1][0] * transition_matrix[0, 1],
                                #chance from loaded to loaded
                                alpha_probs[t - 1][0] * transition_matrix[1, 1]
                                ]),
                            ])
            #normalize for probabilities
            alpha_probs[t] /= np.sum(alpha_probs[t])
            #still need u_t for underflow ?
            #u[t - 1, :] = alpha[t] / alpha[t - 1]
            
    print(alpha[128][0] / alpha[128][1])
    return alpha_probs

In [1214]:
alpha = forward(obs_a, trans_a, emit_a, pi_a)

1.6343228459730739


In [1215]:
print(alpha)

[[0.625      0.375     ]
 [0.62025316 0.37974684]
 [0.62040026 0.37959974]
 [0.62039567 0.37960433]
 [0.62039581 0.37960419]
 [0.62039581 0.37960419]
 [0.24634358 0.75365642]
 [0.64767406 0.35232594]
 [0.61957884 0.38042116]
 [0.62042133 0.37957867]
 [0.24634295 0.75365705]
 [0.26882218 0.73117782]
 [0.64412739 0.35587261]
 [0.61968134 0.38031866]
 [0.62041812 0.37958188]
 [0.62039511 0.37960489]
 [0.62039583 0.37960417]
 [0.62039581 0.37960419]
 [0.62039581 0.37960419]
 [0.62039581 0.37960419]
 [0.62039581 0.37960419]
 [0.62039581 0.37960419]
 [0.62039581 0.37960419]
 [0.62039581 0.37960419]
 [0.62039581 0.37960419]
 [0.24634358 0.75365642]
 [0.64767406 0.35232594]
 [0.61957884 0.38042116]
 [0.62042133 0.37957867]
 [0.62039501 0.37960499]
 [0.62039583 0.37960417]
 [0.62039581 0.37960419]
 [0.62039581 0.37960419]
 [0.62039581 0.37960419]
 [0.62039581 0.37960419]
 [0.62039581 0.37960419]
 [0.62039581 0.37960419]
 [0.24634358 0.75365642]
 [0.26882208 0.73117792]
 [0.6441274  0.3558726 ]


# Backwards Algorithm

In [1217]:
#Modified from from "http://www.adeveloperdiary.com/data-science/machine-learning/forward-and-backward-algorithm-in-hidden-markov-model/"
def backward(observations, transition_matrix, emission_matrix):
    #python indexed 0 so subtract 1 from all dice rolls
    observations = observations - 1
    #get number of observations
    observations_rows = observations.shape[0]
    #get number of states
    K = transition_matrix.shape[0]
    
    #initial probabilities for beta start at T and work backwards
    beta, beta_probs = np.zeros([observations_rows, K]), np.zeros([observations_rows, K])
    beta[observations_rows - 1] = np.array([1, 1])
    beta_probs[observations_rows - 1] = np.array([1, 1])
    
    for t, obs in reversed(list(enumerate(observations))[1:]):
        beta[t - 1] = np.array([
            np.sum([
                #from fair to fair
                transition_matrix[0, 0] * emission_matrix[0][obs] * beta[t][0],
                #from fair to loaded
                transition_matrix[0, 1] * emission_matrix[1][obs] * beta[t][1],
            ]),
            np.sum([
                #from loaded to fair
                transition_matrix[1, 0] * emission_matrix[0][obs] * beta[t][0],
                #from loaded to loaded
                transition_matrix[1, 1] * emission_matrix[1][obs] * beta[t][1]
            ])
        ])
        beta_probs[t - 1] = np.array([
            np.sum([
                #from fair to fair
                transition_matrix[0, 0] * emission_matrix[0][obs] * beta_probs[t][0],
                #from fair to loaded
                transition_matrix[0, 1] * emission_matrix[1][obs] * beta_probs[t][1],
            ]),
            np.sum([
                #from loaded to fair
                transition_matrix[1, 0] * emission_matrix[0][obs] * beta_probs[t][0],
                #from loaded to loaded
                transition_matrix[1, 1] * emission_matrix[1][obs] * beta_probs[t][1]
            ])
        ])
        
        #normalize beta values
        beta_probs[t - 1] /= np.sum(beta_probs[t - 1])
    print(beta[128][0] / beta[128][1])
    
    return beta_probs

In [1218]:
beta = backward(obs_a, trans_a, emit_a)

0.8001349068941145


In [1219]:
print(beta)

[[0.83753763 0.16246237]
 [0.80775169 0.19224831]
 [0.76168793 0.23831207]
 [0.69396316 0.30603684]
 [0.60144619 0.39855381]
 [0.48698444 0.51301556]
 [0.73899454 0.26100546]
 [0.66206804 0.33793196]
 [0.56052515 0.43947485]
 [0.44024075 0.55975925]
 [0.69665882 0.30334118]
 [0.88449408 0.11550592]
 [0.88430652 0.11569348]
 [0.88399063 0.11600937]
 [0.8834588  0.1165412 ]
 [0.88256396 0.11743604]
 [0.88105982 0.11894018]
 [0.87853579 0.12146421]
 [0.87431232 0.12568768]
 [0.86727865 0.13272135]
 [0.85565695 0.14434305]
 [0.83670249 0.16329751]
 [0.80643459 0.19356541]
 [0.75969346 0.24030654]
 [0.6911223  0.3088777 ]
 [0.88137091 0.11862909]
 [0.87905737 0.12094263]
 [0.87518386 0.12481614]
 [0.86872667 0.13127333]
 [0.85804017 0.14195983]
 [0.84056451 0.15943549]
 [0.81253797 0.18746203]
 [0.76896549 0.23103451]
 [0.70439185 0.29560815]
 [0.61518097 0.38481903]
 [0.5031825  0.4968175 ]
 [0.37832098 0.62167902]
 [0.63274854 0.36725146]
 [0.84640431 0.15359569]
 [0.82182856 0.17817144]


# 2. Baum Welch Algorithm

In [958]:
obs_b = pd.read_csv("../datasets/markov/hmm_pb2.csv", header=None).values
obs_b = obs_b[0]
trans_EM = np.random.rand(2, 2)
trans_EM /= trans_EM.sum(axis=1)[:, None]
emit_EM = np.random.rand(2, 6)
emit_EM /= emit_EM.sum(axis=1)[:, None]
pi_EM = np.random.rand(2)
pi_EM /= pi_EM.sum()

#Check initial guesses
print(trans_EM)
print(emit_EM)
print(pi_EM)
#Check their probabilities add to 1
print(trans_EM.sum(axis=1))
print(emit_EM.sum(axis=1))
print(np.sum(pi_EM))

[[0.794 0.206]
 [0.776 0.224]]
[[0.149 0.271 0.02  0.267 0.119 0.175]
 [0.171 0.13  0.2   0.131 0.218 0.149]]
[0.478 0.522]
[1. 1.]
[1. 1.]
0.9999999999999999


In [1221]:
def baum_welch(observations, transition_matrix, emission_matrix, pi, epochs = 50):
    
    observations = observations - 1
    observations_rows = observations.shape[0]
    #number of states
    K = transition_matrix.shape[0]
    
    for epoch in range(epochs):
        #initialize placeholders for observations
        new_transition_matrix = np.zeros((2, 2))
        new_pi = np.zeros(2)
        new_emission_matrix = np.zeros((2, 6))
        fitness = 0
        
        alphas = forward(observations, transition_matrix, emission_matrix, pi)
        betas = backward(observations, transition_matrix, emission_matrix)
        
        #collect probabilities of each observation
        probability_of_obs = pi[0] * betas[0][0] + pi[1] * betas[0][1]
        fitness += probability_of_obs
        
        #xi calculations - probability of being in state 'i' at time 't' 
        #and state 'j' at time 't+1' based on the model
        xi = np.zeros([observations_rows, K, K])
        for t in range(observations_rows - 1):
            denominator = np.dot(np.dot(alphas[t, :].T, transition_matrix) * emission_matrix[:, observations[t + 1]].T, betas[t + 1, :])
            xi[t, 0, 0] = (alphas[t][0] * transition_matrix[0, 0]
                          * emission_matrix[0][observations[t + 1]] * betas[t + 1][0]) / denominator
            xi[t, 0, 1] = (alphas[t][0] * transition_matrix[0, 1]
                          * emission_matrix[1][observations[t + 1]] * betas[t + 1][1]) / denominator
            xi[t, 1, 0] = (alphas[t][1] * transition_matrix[1, 0]
                          * emission_matrix[0][observations[t + 1]] * betas[t + 1][0]) / denominator
            xi[t, 1, 1] = (alphas[t][1] * transition_matrix[1, 1]
                          * emission_matrix[1][observations[t + 1]] * betas[t + 1][1]) / denominator
        
        #gamma stores probability that we are in state 'i' at time t
        gamma = np.zeros([observations_rows, K])
        for t in range(observations_rows - 1):
            gamma[t, 0] = np.sum(xi[t, 0, :])
            gamma[t, 1] = np.sum(xi[t, 1, :])
        
        #recompute initial probabilities for the observation
        new_pi = gamma[0] / np.sum(gamma[0])
        
        # calculate new transition matrix for later update
        new_transition_matrix[0, 0] += np.sum(xi[:, 0, 0]) / np.sum(gamma[:, 0])
        new_transition_matrix[0, 1] += np.sum(xi[:, 0, 1]) / np.sum(gamma[:, 0])
        new_transition_matrix[1, 0] += np.sum(xi[:, 1, 0]) / np.sum(gamma[:, 1])
        new_transition_matrix[1, 1] += np.sum(xi[:, 1, 1]) / np.sum(gamma[:, 1])
        
        # calculate new emission matrix for later update
        emit_denom = np.sum(gamma, axis=0)
        for l in range(emission_matrix.shape[1]):
            #new_emission_matrix[:, l] = np.sum(gamma[observations == l, :]) / emit_denom
            new_emission_matrix[0, l] = np.sum(np.take(gamma[:, 0], np.where(observations == l))) / emit_denom[0]
            new_emission_matrix[1, l] = np.sum(np.take(gamma[:, 1], np.where(observations == l))) / emit_denom[1]
        
        #update all values for probabilities for next epoch
        pi = new_pi
        transition_matrix = new_transition_matrix
        emission_matrix = new_emission_matrix
        
                                                                    
    # Some logging is always good :)
        print('= EPOCH #{} ='.format(epoch))
        print('Transition Matrix:', transition_matrix)
        print('Initial Dice Probability:', pi)
        print('Emission Matrix:', emission_matrix)
        print('Fitness:', fitness)
        print()

In [1183]:
baum_welch(obs_b, trans_EM, emit_EM, pi_EM, epochs = 1000)

= EPOCH #0 =
Transition Matrix: [[0.71655637 0.28344363]
 [0.69781136 0.30218864]]
Initial Dice Probability: [0.3346804 0.6653196]
Emission Matrix: [[0.22717641 0.21679365 0.24130621 0.07142966 0.15794935 0.08534472]
 [0.13603955 0.1725865  0.08334859 0.44244932 0.05669779 0.10887826]]
Fitness: 0.5005978424328097

= EPOCH #1 =
Transition Matrix: [[0.70637389 0.29362611]
 [0.69042981 0.30957019]]
Initial Dice Probability: [0.57419195 0.42580805]
Emission Matrix: [[0.17291581 0.22600451 0.19559263 0.24355826 0.04646592 0.11546287]
 [0.24594632 0.15242039 0.17389019 0.09586813 0.28468624 0.04718873]]
Fitness: 0.4987383208560826

= EPOCH #2 =
Transition Matrix: [[0.70293446 0.29706554]
 [0.68594638 0.31405362]]
Initial Dice Probability: [0.18214002 0.81785998]
Emission Matrix: [[0.2413453  0.17003675 0.20580671 0.19681334 0.15294686 0.03305104]
 [0.1084101  0.26531219 0.15430794 0.19266136 0.06705197 0.21225644]]
Fitness: 0.5000646485009852

= EPOCH #3 =
Transition Matrix: [[0.69879331 0.3

= EPOCH #26 =
Transition Matrix: [[0.61571562 0.38428438]
 [0.59463524 0.40536476]]
Initial Dice Probability: [0.42741257 0.57258743]
Emission Matrix: [[0.23290153 0.1752756  0.1998306  0.18926073 0.14818107 0.05455046]
 [0.14600566 0.23950655 0.17266383 0.20405199 0.09037677 0.1473952 ]]
Fitness: 0.49993285990034675

= EPOCH #27 =
Transition Matrix: [[0.6144934  0.3855066 ]
 [0.59271335 0.40728665]]
Initial Dice Probability: [0.5499881 0.4500119]
Emission Matrix: [[0.12090998 0.24913841 0.17188033 0.21666946 0.12542113 0.1159807 ]
 [0.29326694 0.14201291 0.20970881 0.16835676 0.1224457  0.06420888]]
Fitness: 0.4998835778658395

= EPOCH #28 =
Transition Matrix: [[0.61214466 0.38785534]
 [0.5893726  0.4106274 ]]
Initial Dice Probability: [0.55713915 0.44286085]
Emission Matrix: [[0.24059464 0.12605856 0.22802359 0.17716571 0.13496548 0.09319202]
 [0.13605042 0.30705813 0.13389266 0.2206605  0.10910505 0.09323324]]
Fitness: 0.49987879259254236

= EPOCH #29 =
Transition Matrix: [[0.610827

= EPOCH #52 =
Transition Matrix: [[0.58698551 0.41301449]
 [0.56142156 0.43857844]]
Initial Dice Probability: [0.60194095 0.39805905]
Emission Matrix: [[0.23359877 0.14266996 0.22071166 0.17880698 0.13284586 0.09136677]
 [0.15005846 0.277113   0.14778696 0.21643856 0.11306242 0.0955406 ]]
Fitness: 0.4997506673423988

= EPOCH #53 =
Transition Matrix: [[0.58646429 0.41353571]
 [0.56075784 0.43924216]]
Initial Dice Probability: [0.63879797 0.36120203]
Emission Matrix: [[0.19059365 0.23802349 0.13198794 0.22717858 0.11296618 0.09925016]
 [0.20442999 0.15670587 0.25966959 0.1554471  0.13814124 0.08560622]]
Fitness: 0.5005136843862636

= EPOCH #54 =
Transition Matrix: [[0.58558221 0.41441779]
 [0.56007139 0.43992861]]
Initial Dice Probability: [0.59346357 0.40653643]
Emission Matrix: [[0.21129094 0.19730513 0.22344141 0.13797852 0.14470089 0.0852831 ]
 [0.17884171 0.20780527 0.14567123 0.2658958  0.09885174 0.10293425]]
Fitness: 0.49877517647555747

= EPOCH #55 =
Transition Matrix: [[0.58473

= EPOCH #78 =
Transition Matrix: [[0.57329479 0.42670521]
 [0.54546654 0.45453346]]
Initial Dice Probability: [0.61398851 0.38601149]
Emission Matrix: [[0.20988391 0.19532346 0.21963056 0.14725576 0.14196416 0.08594215]
 [0.18119664 0.20991688 0.15183247 0.25221341 0.10306195 0.10177864]]
Fitness: 0.49879831620332415

= EPOCH #79 =
Transition Matrix: [[0.57280693 0.42719307]
 [0.54521882 0.45478118]]
Initial Dice Probability: [0.68338393 0.31661607]
Emission Matrix: [[0.1797288  0.21383266 0.1810669  0.22580796 0.09371357 0.1058501 ]
 [0.21706115 0.18787832 0.19744033 0.15903851 0.16050592 0.07807577]]
Fitness: 0.5005724270986114

= EPOCH #80 =
Transition Matrix: [[0.57265079 0.42734921]
 [0.54500642 0.45499358]]
Initial Dice Probability: [0.55984448 0.44015552]
Emission Matrix: [[0.22213896 0.18269607 0.19760638 0.18588768 0.14207291 0.06959801]
 [0.16624128 0.22519034 0.17762267 0.2068485  0.1025773  0.1215199 ]]
Fitness: 0.49976722275446905

= EPOCH #81 =
Transition Matrix: [[0.5721

= EPOCH #104 =
Transition Matrix: [[0.56522246 0.43477754]
 [0.53563872 0.46436128]]
Initial Dice Probability: [0.58224287 0.41775713]
Emission Matrix: [[0.21981535 0.18421726 0.19747119 0.1850664  0.140772   0.0726578 ]
 [0.16976758 0.2227958  0.17807168 0.20750141 0.10467107 0.11719245]]
Fitness: 0.49971567803388917

= EPOCH #105 =
Transition Matrix: [[0.56481714 0.43518286]
 [0.53500881 0.46499119]]
Initial Dice Probability: [0.65138139 0.34861861]
Emission Matrix: [[0.15629996 0.23038264 0.17593759 0.20926356 0.12012369 0.10799256]
 [0.24199523 0.17025043 0.20261157 0.17991236 0.12858032 0.07665009]]
Fitness: 0.5001335483312132

= EPOCH #106 =
Transition Matrix: [[0.56464705 0.43535295]
 [0.53454456 0.46545544]]
Initial Dice Probability: [0.63672398 0.36327602]
Emission Matrix: [[0.22591462 0.15989135 0.21263751 0.1808957  0.13122584 0.08943498]
 [0.16258214 0.25128129 0.16031701 0.2124022  0.11579471 0.09762264]]
Fitness: 0.4996506224201356

= EPOCH #107 =
Transition Matrix: [[0.5

= EPOCH #130 =
Transition Matrix: [[0.55962719 0.44037281]
 [0.52797757 0.47202243]]
Initial Dice Probability: [0.64370903 0.35629097]
Emission Matrix: [[0.22396386 0.16418143 0.21060525 0.18138639 0.13095815 0.08890492]
 [0.16543484 0.24547092 0.16315678 0.21153397 0.11625137 0.09815212]]
Fitness: 0.4996263770535904

= EPOCH #131 =
Transition Matrix: [[0.55954483 0.44045517]
 [0.52779454 0.47220546]]
Initial Dice Probability: [0.669523 0.330477]
Emission Matrix: [[0.18660017 0.22937938 0.15269453 0.21787299 0.11515804 0.09829489]
 [0.20824078 0.17087162 0.22930505 0.16985616 0.13430702 0.08741937]]
Fitness: 0.5005913512257123

= EPOCH #132 =
Transition Matrix: [[0.55924099 0.44075901]
 [0.52753398 0.47246602]]
Initial Dice Probability: [0.63642529 0.36357471]
Emission Matrix: [[0.20859213 0.1925406  0.21473411 0.15893684 0.13846669 0.08672962]
 [0.18334035 0.21270296 0.15897633 0.23653267 0.10793627 0.10051143]]
Fitness: 0.4988922905159654

= EPOCH #133 =
Transition Matrix: [[0.559039

= EPOCH #156 =
Transition Matrix: [[0.55558625 0.44441375]
 [0.52249672 0.47750328]]
Initial Dice Probability: [0.64192535 0.35807465]
Emission Matrix: [[0.20837935 0.19167961 0.21333548 0.16219265 0.13749233 0.08692059]
 [0.18373588 0.21353511 0.16088395 0.23241981 0.10921302 0.10021223]]
Fitness: 0.4989317064917631

= EPOCH #157 =
Transition Matrix: [[0.5554375  0.4445625 ]
 [0.52244368 0.47755632]]
Initial Dice Probability: [0.69044187 0.30955813]
Emission Matrix: [[0.18240883 0.21305183 0.17826925 0.22017865 0.10317765 0.1029138 ]
 [0.21278903 0.18963301 0.20002793 0.16761803 0.14761965 0.08231236]]
Fitness: 0.5006600743230151

= EPOCH #158 =
Transition Matrix: [[0.55540841 0.44459159]
 [0.52239903 0.47760097]]
Initial Dice Probability: [0.61127988 0.38872012]
Emission Matrix: [[0.21654483 0.1862331  0.19762452 0.18370515 0.13890491 0.0769875 ]
 [0.17441475 0.21978198 0.17827424 0.20859919 0.10746965 0.1114602 ]]
Fitness: 0.49962161938889915

= EPOCH #159 =
Transition Matrix: [[0.5

= EPOCH #182 =
Transition Matrix: [[0.55260492 0.44739508]
 [0.51832782 0.48167218]]
Initial Dice Probability: [0.61931467 0.38068533]
Emission Matrix: [[0.21557488 0.18678142 0.19778424 0.1832451  0.13832487 0.07828949]
 [0.17573256 0.218982   0.17820585 0.20897052 0.10829298 0.1098161 ]]
Fitness: 0.49958686605512137

= EPOCH #183 =
Transition Matrix: [[0.55233037 0.44766963]
 [0.5179299  0.4820701 ]]
Initial Dice Probability: [0.67417135 0.32582865]
Emission Matrix: [[0.16715532 0.22436697 0.17695171 0.20800049 0.11813861 0.10538691]
 [0.22877739 0.17778877 0.20106153 0.18177756 0.13059003 0.08000471]]
Fitness: 0.5002253998998593

= EPOCH #184 =
Transition Matrix: [[0.55235572 0.44764428]
 [0.51778911 0.48221089]]
Initial Dice Probability: [0.6527522 0.3472478]
Emission Matrix: [[0.22092964 0.17072964 0.20753461 0.1820328  0.13072774 0.08804556]
 [0.16966019 0.23699365 0.16726494 0.2103819  0.11671845 0.09898085]]
Fitness: 0.4995845313121629

= EPOCH #185 =
Transition Matrix: [[0.552

= EPOCH #208 =
Transition Matrix: [[0.5501415  0.4498585 ]
 [0.51444678 0.48555322]]
Initial Dice Probability: [0.65508295 0.34491705]
Emission Matrix: [[0.21993912 0.17280617 0.20657884 0.18219598 0.13071664 0.08776325]
 [0.17098826 0.23439471 0.16850507 0.21007367 0.11679371 0.09924457]]
Fitness: 0.4995687383429027

= EPOCH #209 =
Transition Matrix: [[0.55010611 0.44989389]
 [0.51433113 0.48566887]]
Initial Dice Probability: [0.6790252 0.3209748]
Emission Matrix: [[0.18468797 0.22576717 0.1611401  0.21417929 0.11591613 0.09830934]
 [0.2099209  0.17596494 0.21855892 0.17483628 0.1331054  0.08761356]]
Fitness: 0.5005817596681164

= EPOCH #210 =
Transition Matrix: [[0.54994145 0.45005855]
 [0.51417271 0.48582729]]
Initial Dice Probability: [0.64977616 0.35022384]
Emission Matrix: [[0.20824777 0.19021801 0.21101244 0.16740714 0.13594199 0.08717265]
 [0.18412097 0.21491846 0.1639363  0.22603344 0.11118423 0.09980661]]
Fitness: 0.49900779729930245

= EPOCH #211 =
Transition Matrix: [[0.549

= EPOCH #234 =
Transition Matrix: [[0.54814025 0.45185975]
 [0.5113141  0.4886859 ]]
Initial Dice Probability: [0.65199259 0.34800741]
Emission Matrix: [[0.20827744 0.18972198 0.21021234 0.16911516 0.135439   0.08723408]
 [0.18416587 0.21537828 0.16495583 0.22399082 0.1118097  0.0996995 ]]
Fitness: 0.49903636534868795

= EPOCH #235 =
Transition Matrix: [[0.54806924 0.45193076]
 [0.51129007 0.48870993]]
Initial Dice Probability: [0.69196536 0.30803464]
Emission Matrix: [[0.18338282 0.213325   0.17673457 0.21737251 0.10761288 0.10157222]
 [0.21126961 0.18968714 0.20137501 0.17146978 0.14211271 0.08408575]]
Fitness: 0.5006821434310758

= EPOCH #236 =
Transition Matrix: [[0.5480656  0.4519344 ]
 [0.51127762 0.48872238]]
Initial Dice Probability: [0.63174012 0.36825988]
Emission Matrix: [[0.21398583 0.18759165 0.19821829 0.18243721 0.13730995 0.08045708]
 [0.17784171 0.21779567 0.17791397 0.20961379 0.10968288 0.10715199]]
Fitness: 0.49952053931125334

= EPOCH #237 =
Transition Matrix: [[0.

= EPOCH #260 =
Transition Matrix: [[0.54656474 0.45343526]
 [0.5087697  0.4912303 ]]
Initial Dice Probability: [0.63557928 0.36442072]
Emission Matrix: [[0.21346022 0.18782477 0.19842357 0.18215881 0.13694469 0.08118794]
 [0.17852773 0.21744636 0.17775541 0.20982997 0.11016758 0.10627295]]
Fitness: 0.49949548629566587

= EPOCH #261 =
Transition Matrix: [[0.54635385 0.45364615]
 [0.50847875 0.49152125]]
Initial Dice Probability: [0.68323631 0.31676369]
Emission Matrix: [[0.17268623 0.22132839 0.17719147 0.20782626 0.11701885 0.1039488 ]
 [0.2223521  0.1814274  0.20059987 0.18218738 0.13167792 0.08175532]]
Fitness: 0.5002967165880114

= EPOCH #262 =
Transition Matrix: [[0.54642964 0.45357036]
 [0.50844082 0.49155918]]
Initial Dice Probability: [0.65819851 0.34180149]
Emission Matrix: [[0.21817611 0.1763717  0.20497641 0.18240301 0.13079436 0.08727841]
 [0.17329437 0.23002224 0.17055112 0.20963049 0.11681732 0.09968446]]
Fitness: 0.4995363618745696

= EPOCH #263 =
Transition Matrix: [[0.5

= EPOCH #286 =
Transition Matrix: [[0.54516936 0.45483064]
 [0.506242   0.493758  ]]
Initial Dice Probability: [0.65892559 0.34107441]
Emission Matrix: [[0.21753926 0.17760475 0.2044389  0.18244644 0.13085603 0.08711462]
 [0.17411013 0.22853477 0.17123007 0.20950801 0.11678901 0.09982801]]
Fitness: 0.49952294189455576

= EPOCH #287 =
Transition Matrix: [[0.54513604 0.45486396]
 [0.50614115 0.49385885]]
Initial Dice Probability: [0.68290856 0.31709144]
Emission Matrix: [[0.18359357 0.22358481 0.16586547 0.21221981 0.11621355 0.09852279]
 [0.2108266  0.17884422 0.21286496 0.17736391 0.1326015  0.08749882]]
Fitness: 0.5005698475427682

= EPOCH #288 =
Transition Matrix: [[0.54503849 0.45496151]
 [0.50603342 0.49396658]]
Initial Dice Probability: [0.65520494 0.34479506]
Emission Matrix: [[0.20844226 0.18885174 0.20873481 0.17209598 0.13457124 0.08730397]
 [0.18412483 0.21616851 0.16679866 0.22047856 0.11287536 0.09955408]]
Fitness: 0.49909067591399203

= EPOCH #289 =
Transition Matrix: [[0.

= EPOCH #312 =
Transition Matrix: [[0.54396346 0.45603654]
 [0.5040578  0.4959422 ]]
Initial Dice Probability: [0.6560508 0.3439492]
Emission Matrix: [[0.20854007 0.18855191 0.20818407 0.1731377  0.13427239 0.08731386]
 [0.18406943 0.21643403 0.16747304 0.21926567 0.11323915 0.09951867]]
Fitness: 0.4991109778692001

= EPOCH #313 =
Transition Matrix: [[0.5439183  0.4560817 ]
 [0.50403513 0.49596487]]
Initial Dice Probability: [0.69144134 0.30855866]
Emission Matrix: [[0.18375343 0.21384021 0.17582916 0.21554215 0.11021339 0.10082166]
 [0.21061919 0.18934942 0.20212191 0.17384856 0.13901185 0.08504907]]
Fitness: 0.500685821405162

= EPOCH #314 =
Transition Matrix: [[0.54392436 0.45607564]
 [0.50403203 0.49596797]]
Initial Dice Probability: [0.6417622 0.3582378]
Emission Matrix: [[0.21254551 0.18816753 0.1988806  0.18167198 0.13624826 0.08248612]
 [0.17971154 0.21690776 0.17738301 0.21019414 0.11106993 0.10473361]]
Fitness: 0.4994472698720854

= EPOCH #315 =
Transition Matrix: [[0.5437433

= EPOCH #338 =
Transition Matrix: [[0.54299401 0.45700599]
 [0.50222765 0.49777235]]
Initial Dice Probability: [0.64368878 0.35631122]
Emission Matrix: [[0.21222918 0.18826108 0.19907545 0.1815068  0.13598135 0.08294613]
 [0.18011908 0.21674726 0.1772196  0.21031103 0.11140851 0.10419452]]
Fitness: 0.49942897969422795

= EPOCH #339 =
Transition Matrix: [[0.54282393 0.45717607]
 [0.50200057 0.49799943]]
Initial Dice Probability: [0.68674957 0.31325043]
Emission Matrix: [[0.17601778 0.21953238 0.17714239 0.20798545 0.11634239 0.1029796 ]
 [0.21856249 0.18354289 0.20052229 0.18216109 0.13231065 0.08290058]]
Fitness: 0.5003575170246453

= EPOCH #340 =
Transition Matrix: [[0.54291587 0.45708413]
 [0.50200715 0.49799285]]
Initial Dice Probability: [0.65957422 0.34042578]
Emission Matrix: [[0.21633371 0.17983493 0.2034997  0.18247545 0.13102384 0.08683238]
 [0.17563077 0.22587368 0.17241153 0.20933695 0.11668129 0.10006577]]
Fitness: 0.4994943610704016

= EPOCH #341 =
Transition Matrix: [[0.5

= EPOCH #364 =
Transition Matrix: [[0.54211187 0.45788813]
 [0.50036845 0.49963155]]
Initial Dice Probability: [0.65952832 0.34047168]
Emission Matrix: [[0.21587737 0.18063814 0.20317524 0.18246675 0.13110464 0.08673786]
 [0.17619874 0.22492378 0.17281954 0.20929403 0.11662262 0.10014128]]
Fitness: 0.4994822937085071

= EPOCH #365 =
Transition Matrix: [[0.54207222 0.45792778]
 [0.50027045 0.49972955]]
Initial Dice Probability: [0.68413761 0.31586239]
Emission Matrix: [[0.18296335 0.22204167 0.16885279 0.21105899 0.11630981 0.09877339]
 [0.21130265 0.18079559 0.2093667  0.17884027 0.13238389 0.08731089]]
Fitness: 0.5005625605252604

= EPOCH #366 =
Transition Matrix: [[0.54201711 0.45798289]
 [0.50019634 0.49980366]]
Initial Dice Probability: [0.65702153 0.34297847]
Emission Matrix: [[0.20878206 0.18802619 0.20711713 0.17503006 0.13373876 0.0873058 ]
 [0.1839057  0.21688616 0.16876174 0.21707946 0.11388626 0.09948068]]
Fitness: 0.49914947254957653

= EPOCH #367 =
Transition Matrix: [[0.5

= EPOCH #390 =
Transition Matrix: [[0.54131633 0.45868367]
 [0.49868405 0.50131595]]
Initial Dice Probability: [0.65712348 0.34287652]
Emission Matrix: [[0.2088924  0.18784671 0.20670514 0.17571268 0.13355035 0.08729272]
 [0.1838247  0.21703465 0.16925352 0.21629567 0.11411449 0.09947697]]
Fitness: 0.49916379726924553

= EPOCH #391 =
Transition Matrix: [[0.54128002 0.45871998]
 [0.49865557 0.50134443]]
Initial Dice Probability: [0.6897893 0.3102107]
Emission Matrix: [[0.18385388 0.21438024 0.17530472 0.21420108 0.11189243 0.10036765]
 [0.21034371 0.18893172 0.20251176 0.1755311  0.13705259 0.08562912]]
Fitness: 0.5006816782554536

= EPOCH #392 =
Transition Matrix: [[0.54129254 0.45870746]
 [0.4986567  0.5013433 ]]
Initial Dice Probability: [0.64668624 0.35331376]
Emission Matrix: [[0.21166479 0.18838213 0.19948536 0.18122536 0.13545304 0.08378932]
 [0.18084658 0.21650509 0.17687141 0.21049507 0.11206762 0.10321423]]
Fitness: 0.49939372777006796

= EPOCH #393 =
Transition Matrix: [[0.54

= EPOCH #416 =
Transition Matrix: [[0.54067548 0.45932452]
 [0.49724375 0.50275625]]
Initial Dice Probability: [0.64754257 0.35245743]
Emission Matrix: [[0.21146632 0.18840627 0.19965317 0.18113347 0.13524514 0.08409563]
 [0.18110348 0.2164369  0.17672799 0.210548   0.11232323 0.10286041]]
Fitness: 0.49938034666176584

= EPOCH #417 =
Transition Matrix: [[0.54053422 0.45946578]
 [0.49705893 0.50294107]]
Initial Dice Probability: [0.68733624 0.31266376]
Emission Matrix: [[0.17818535 0.21839872 0.1769744  0.20824294 0.11593292 0.10226567]
 [0.21612148 0.1848751  0.20060363 0.18199596 0.13267474 0.0837291 ]]
Fitness: 0.5004094605396094

= EPOCH #418 =
Transition Matrix: [[0.54063047 0.45936953]
 [0.49708738 0.50291262]]
Initial Dice Probability: [0.65887726 0.34112274]
Emission Matrix: [[0.21498769 0.18212969 0.20259982 0.18241634 0.13128811 0.08657835]
 [0.17729481 0.2231703  0.17354619 0.20924619 0.1164823  0.1002602 ]]
Fitness: 0.4994564727177402

= EPOCH #419 =
Transition Matrix: [[0.5

= EPOCH #442 =
Transition Matrix: [[0.54009052 0.45990948]
 [0.49577621 0.50422379]]
Initial Dice Probability: [0.65839282 0.34160718]
Emission Matrix: [[0.21464339 0.18267828 0.20239945 0.18238445 0.13136773 0.08652671]
 [0.17771524 0.22252836 0.17380132 0.20924059 0.11641963 0.10029486]]
Fitness: 0.4994455771450973

= EPOCH #443 =
Transition Matrix: [[0.54004376 0.45995624]
 [0.49567818 0.50432182]]
Initial Dice Probability: [0.68378082 0.31621918]
Emission Matrix: [[0.18261904 0.22086941 0.17085496 0.21034045 0.11630804 0.0990081 ]
 [0.21152028 0.1822353  0.2070596  0.17975794 0.1323042  0.08712268]]
Fitness: 0.5005599160514377

= EPOCH #444 =
Transition Matrix: [[0.54001906 0.45998094]
 [0.4956294  0.5043706 ]]
Initial Dice Probability: [0.65678568 0.34321432]
Emission Matrix: [[0.20913445 0.18753751 0.20588976 0.17697884 0.13320945 0.08725   ]
 [0.1836404  0.21727807 0.17021818 0.21484728 0.11452845 0.09948761]]
Fitness: 0.4991907558354687

= EPOCH #445 =
Transition Matrix: [[0.53

= EPOCH #468 =
Transition Matrix: [[0.53954517 0.46045483]
 [0.49439964 0.50560036]]
Initial Dice Probability: [0.65642685 0.34357315]
Emission Matrix: [[0.2092367  0.18743472 0.20557009 0.17744323 0.13308818 0.08722707]
 [0.18356098 0.21735338 0.1705935  0.21431738 0.11467652 0.09949824]]
Fitness: 0.4992006806914438

= EPOCH #469 =
Transition Matrix: [[0.53951072 0.46048928]
 [0.49436339 0.50563661]]
Initial Dice Probability: [0.68740918 0.31259082]
Emission Matrix: [[0.18382468 0.21486984 0.17502155 0.21316725 0.1130306  0.10008609]
 [0.21024969 0.18853778 0.20268083 0.17679784 0.13573995 0.0859939 ]]
Fitness: 0.5006740802528314

= EPOCH #470 =
Transition Matrix: [[0.53952926 0.46047074]
 [0.49436795 0.50563205]]
Initial Dice Probability: [0.64864562 0.35135438]
Emission Matrix: [[0.21110984 0.18841493 0.19999652 0.18098493 0.13482742 0.08466635]
 [0.18156879 0.21634469 0.17643444 0.21061721 0.11283097 0.1022039 ]]
Fitness: 0.4993545452082857

= EPOCH #471 =
Transition Matrix: [[0.53

= EPOCH #494 =
Transition Matrix: [[0.53911007 0.46088993]
 [0.49320273 0.50679727]]
Initial Dice Probability: [0.64883199 0.35116801]
Emission Matrix: [[0.21098437 0.18840375 0.20013393 0.18094014 0.13466143 0.08487638]
 [0.1817347  0.21632419 0.17631729 0.21063006 0.11303074 0.10196302]]
Fitness: 0.49934474416904434

= EPOCH #495 =
Transition Matrix: [[0.53898991 0.46101009]
 [0.49304715 0.50695285]]
Initial Dice Probability: [0.68618185 0.31381815]
Emission Matrix: [[0.17965269 0.21766497 0.17676338 0.20850819 0.11569258 0.10171819]
 [0.21447479 0.18574464 0.2007483  0.18180316 0.13287172 0.08435738]]
Fitness: 0.5004531542044615

= EPOCH #496 =
Transition Matrix: [[0.53908583 0.46091417]
 [0.493087   0.506913  ]]
Initial Dice Probability: [0.65696587 0.34303413]
Emission Matrix: [[0.21396296 0.18371122 0.20204426 0.18230013 0.13153775 0.08644368]
 [0.17854054 0.22132285 0.17425939 0.20925098 0.11628408 0.10034215]]
Fitness: 0.4994223600304904

= EPOCH #497 =
Transition Matrix: [[0.5

= EPOCH #520 =
Transition Matrix: [[0.53871861 0.46128139]
 [0.49199005 0.50800995]]
Initial Dice Probability: [0.65620772 0.34379228]
Emission Matrix: [[0.21369709 0.18409528 0.20192137 0.18225922 0.13160831 0.08641873]
 [0.1788612  0.22087535 0.1744208  0.20926283 0.1162275  0.10035231]]
Fitness: 0.4994126173563561

= EPOCH #521 =
Transition Matrix: [[0.53866579 0.46133421]
 [0.49189155 0.50810845]]
Initial Dice Probability: [0.68235841 0.31764159]
Emission Matrix: [[0.18245284 0.21995059 0.17223738 0.20989161 0.11625839 0.09920919]
 [0.21158209 0.18334129 0.20548001 0.18034332 0.1322943  0.08695898]]
Fitness: 0.5005608445025804

= EPOCH #522 =
Transition Matrix: [[0.53866423 0.46133577]
 [0.49186297 0.50813703]]
Initial Dice Probability: [0.65524559 0.34475441]
Emission Matrix: [[0.20945056 0.1872639  0.20493206 0.17831413 0.1328686  0.08717075]
 [0.18339372 0.21746624 0.17133846 0.2133245  0.11494694 0.09953015]]
Fitness: 0.4992190962748142

= EPOCH #523 =
Transition Matrix: [[0.53

= EPOCH #546 =
Transition Matrix: [[0.53834339 0.46165661]
 [0.49082311 0.50917689]]
Initial Dice Probability: [0.65457979 0.34542021]
Emission Matrix: [[0.20953771 0.18720999 0.20468061 0.17863627 0.13279079 0.08714463]
 [0.18332553 0.21749606 0.1716307  0.21295713 0.11504399 0.09954659]]
Fitness: 0.49922575147328774

= EPOCH #547 =
Transition Matrix: [[0.5383076  0.4616924 ]
 [0.49077887 0.50922113]]
Initial Dice Probability: [0.68452077 0.31547923]
Emission Matrix: [[0.1837351  0.21528511 0.17489073 0.21235409 0.1138222  0.09991278]
 [0.21024573 0.18820211 0.20271531 0.17777878 0.13483176 0.08622631]]
Fitness: 0.5006652972347088

= EPOCH #548 =
Transition Matrix: [[0.53833235 0.46166765]
 [0.4907872  0.5092128 ]]
Initial Dice Probability: [0.64870555 0.35129445]
Emission Matrix: [[0.21076038 0.1883561  0.20041026 0.18087589 0.13432645 0.08527092]
 [0.18203623 0.2163098  0.1760831  0.21062895 0.11343081 0.10151111]]
Fitness: 0.499325818999779

= EPOCH #549 =
Transition Matrix: [[0.53

= EPOCH #572 =
Transition Matrix: [[0.53805043 0.46194957]
 [0.48979272 0.51020728]]
Initial Dice Probability: [0.64844345 0.35155655]
Emission Matrix: [[0.21068249 0.18832781 0.2005192  0.18086041 0.1341931  0.08541699]
 [0.1821437  0.21631388 0.17599152 0.21061802 0.11358904 0.10134384]]
Fitness: 0.49931861377087705

= EPOCH #573 =
Transition Matrix: [[0.53794586 0.46205414]
 [0.48965772 0.51034228]]
Initial Dice Probability: [0.68392365 0.31607635]
Emission Matrix: [[0.18066641 0.21718935 0.17654664 0.20874597 0.11556029 0.10129135]
 [0.21333551 0.18631946 0.20091062 0.1816261  0.13296424 0.08484406]]
Fitness: 0.5004892275399

= EPOCH #574 =
Transition Matrix: [[0.53803975 0.46196025]
 [0.48970368 0.51029632]]
Initial Dice Probability: [0.65428023 0.34571977]
Emission Matrix: [[0.21316886 0.18482337 0.20170642 0.18216401 0.13175443 0.08638292]
 [0.17949566 0.22002707 0.17471009 0.20929947 0.11611042 0.10035728]]
Fitness: 0.4993919853372364

= EPOCH #575 =
Transition Matrix: [[0.5379

= EPOCH #598 =
Transition Matrix: [[0.53779533 0.46220467]
 [0.48875782 0.51124218]]
Initial Dice Probability: [0.65334019 0.34665981]
Emission Matrix: [[0.21296183 0.18509538 0.20163362 0.18212138 0.13181359 0.0863742 ]
 [0.17974353 0.21970985 0.17481143 0.20931865 0.11606322 0.10035332]]
Fitness: 0.49938338307341046

= EPOCH #599 =
Transition Matrix: [[0.53773779 0.46226221]
 [0.48865909 0.51134091]]
Initial Dice Probability: [0.6801732 0.3198268]
Emission Matrix: [[0.18239517 0.21922243 0.1732056  0.20961594 0.11618763 0.09937323]
 [0.21155357 0.18420624 0.20437666 0.1807183  0.132319   0.08682622]]
Fitness: 0.5005641905026434

= EPOCH #600 =
Transition Matrix: [[0.53775442 0.46224558]
 [0.48864704 0.51135296]]
Initial Dice Probability: [0.65282361 0.34717639]
Emission Matrix: [[0.20971542 0.18712659 0.20417779 0.17924348 0.13265119 0.08708554]
 [0.18318728 0.21752884 0.17221329 0.21226358 0.11522103 0.09958598]]
Fitness: 0.4992378180421375

= EPOCH #601 =
Transition Matrix: [[0.537

= EPOCH #624 =
Transition Matrix: [[0.53754472 0.46245528]
 [0.48774359 0.51225641]]
Initial Dice Probability: [0.65194457 0.34805543]
Emission Matrix: [[0.20978635 0.18710311 0.20397961 0.17946883 0.13260244 0.08705965]
 [0.18313262 0.21753135 0.17244238 0.21200547 0.11528427 0.0996039 ]]
Fitness: 0.4992420488513313

= EPOCH #625 =
Transition Matrix: [[0.53750604 0.46249396]
 [0.48769176 0.51230824]]
Initial Dice Probability: [0.68126129 0.31873871]
Emission Matrix: [[0.18362165 0.21562397 0.17485318 0.21171144 0.11437973 0.09981002]
 [0.21028472 0.18793137 0.20267179 0.17854672 0.13419213 0.08637326]]
Fitness: 0.5006565564168235

= EPOCH #626 =
Transition Matrix: [[0.53753727 0.46246273]
 [0.4877044  0.5122956 ]]
Initial Dice Probability: [0.64747524 0.35252476]
Emission Matrix: [[0.21054606 0.18825444 0.20073566 0.18084735 0.13392423 0.08569226]
 [0.18233805 0.21633876 0.17581145 0.21057691 0.11390658 0.10102825]]
Fitness: 0.4993046547099629

= EPOCH #627 =
Transition Matrix: [[0.53

= EPOCH #650 =
Transition Matrix: [[0.53735698 0.46264302]
 [0.48683473 0.51316527]]
Initial Dice Probability: [0.64690011 0.35309989]
Emission Matrix: [[0.21049996 0.18821911 0.2008201  0.18084908 0.13381744 0.08579432]
 [0.1824067  0.21635479 0.17574209 0.21055324 0.11403222 0.10091096]]
Fitness: 0.49929931640210545

= EPOCH #651 =
Transition Matrix: [[0.53726385 0.46273615]
 [0.48671421 0.51328579]]
Initial Dice Probability: [0.68094019 0.31905981]
Emission Matrix: [[0.18137277 0.21688632 0.1763425  0.20894528 0.11549593 0.1009572 ]
 [0.21253685 0.18669854 0.20106832 0.18147933 0.13299293 0.08522403]]
Fitness: 0.5005184486292619

= EPOCH #652 =
Transition Matrix: [[0.53735538 0.46264462]
 [0.48676358 0.51323642]]
Initial Dice Probability: [0.65107234 0.34892766]
Emission Matrix: [[0.2125503  0.18561218 0.20151013 0.18202706 0.13193385 0.08636647]
 [0.18023531 0.21910579 0.1749911  0.20936507 0.11596799 0.10033475]]
Fitness: 0.4993652794755665

= EPOCH #653 =
Transition Matrix: [[0.5

= EPOCH #676 =
Transition Matrix: [[0.53720351 0.46279649]
 [0.48593004 0.51406996]]
Initial Dice Probability: [0.65000607 0.34999393]
Emission Matrix: [[0.21238916 0.18580537 0.20147018 0.18198637 0.1319818  0.08636712]
 [0.18042768 0.2188792  0.17505301 0.20938637 0.1159304  0.10032334]]
Fitness: 0.49935777768367173

= EPOCH #677 =
Transition Matrix: [[0.53714242 0.46285758]
 [0.48583133 0.51416867]]
Initial Dice Probability: [0.67742305 0.32257695]
Emission Matrix: [[0.18240024 0.21864521 0.17388677 0.20945437 0.11611045 0.09950297]
 [0.21147717 0.18488661 0.20359856 0.18095536 0.13235917 0.08672314]]
Fitness: 0.5005689441226525

= EPOCH #678 =
Transition Matrix: [[0.53717363 0.46282637]
 [0.485833   0.514167  ]]
Initial Dice Probability: [0.64978377 0.35021623]
Emission Matrix: [[0.20992882 0.18707308 0.20358403 0.179894   0.13251679 0.08700328]
 [0.18302435 0.21751746 0.17289919 0.21151651 0.1153987  0.09964378]]
Fitness: 0.4992494306963454

= EPOCH #679 =
Transition Matrix: [[0.5

= EPOCH #702 =
Transition Matrix: [[0.53704892 0.46295108]
 [0.48503223 0.51496777]]
Initial Dice Probability: [0.6487531 0.3512469]
Emission Matrix: [[0.20998499 0.18706769 0.20342858 0.1800517  0.13248776 0.08697929]
 [0.18298238 0.21750472 0.17307865 0.21133416 0.11543908 0.09966101]]
Fitness: 0.49925188527285913

= EPOCH #703 =
Transition Matrix: [[0.53700668 0.46299332]
 [0.48497345 0.51502655]]
Initial Dice Probability: [0.67772373 0.32227627]
Emission Matrix: [[0.18350365 0.21589375 0.17486933 0.21120533 0.11477396 0.09975398]
 [0.21034163 0.18772053 0.20258762 0.17914888 0.1337377  0.08646364]]
Fitness: 0.5006484700043268

= EPOCH #704 =
Transition Matrix: [[0.53704452 0.46295548]
 [0.48499087 0.51500913]]
Initial Dice Probability: [0.64533604 0.35466396]
Emission Matrix: [[0.21042238 0.18813694 0.20098649 0.18086479 0.1336029  0.0859865 ]
 [0.18252915 0.21639771 0.17560736 0.21049245 0.11428406 0.10068927]]
Fitness: 0.49928891604295017

= EPOCH #705 =
Transition Matrix: [[0.53

= EPOCH #728 =
Transition Matrix: [[0.53694303 0.46305697]
 [0.48421628 0.51578372]]
Initial Dice Probability: [0.64453672 0.35546328]
Emission Matrix: [[0.2103977  0.18810008 0.20105094 0.18087559 0.13351809 0.08605759]
 [0.18257155 0.21641874 0.17555605 0.21046335 0.11438347 0.10060684]]
Fitness: 0.49928491128531394

= EPOCH #729 =
Transition Matrix: [[0.53685816 0.46314184]
 [0.48410583 0.51589417]]
Initial Dice Probability: [0.67747084 0.32252916]
Emission Matrix: [[0.18186494 0.21670067 0.17615904 0.2091062  0.11547277 0.10069638]
 [0.21197421 0.18694463 0.20121131 0.18136452 0.13298457 0.08552075]]
Fitness: 0.5005416615028625

= EPOCH #730 =
Transition Matrix: [[0.53694762 0.46305238]
 [0.48415726 0.51584274]]
Initial Dice Probability: [0.64749838 0.35250162]
Emission Matrix: [[0.21206963 0.18617191 0.20140677 0.18189862 0.13207815 0.08637492]
 [0.1808092  0.21844721 0.17516032 0.20943419 0.11585579 0.10029329]]
Fitness: 0.49934208023903337

= EPOCH #731 =
Transition Matrix: [[0.

= EPOCH #754 =
Transition Matrix: [[0.53686848 0.46313152]
 [0.48341039 0.51658961]]
Initial Dice Probability: [0.64634199 0.35365801]
Emission Matrix: [[0.21194496 0.18630852 0.20138838 0.18186151 0.13211621 0.08638042]
 [0.18095821 0.21828519 0.17519611 0.20945503 0.11582676 0.10027871]]
Fitness: 0.49933561168675783

= EPOCH #755 =
Transition Matrix: [[0.53680471 0.46319529]
 [0.48331187 0.51668813]]
Initial Dice Probability: [0.67424767 0.32575233]
Emission Matrix: [[0.18243802 0.21819039 0.17436458 0.20936878 0.11603469 0.09960354]
 [0.21138015 0.18542109 0.20304857 0.18110029 0.1324044  0.0866455 ]]
Fitness: 0.5005742912876735

= EPOCH #756 =
Transition Matrix: [[0.53684779 0.46315221]
 [0.48332503 0.51667497]]
Initial Dice Probability: [0.6463028 0.3536972]
Emission Matrix: [[0.21009683 0.18706825 0.20311954 0.18034846 0.1324388  0.08692812]
 [0.18290047 0.21746623 0.1734357  0.21098863 0.11551088 0.09969808]]
Fitness: 0.4992558665485013

= EPOCH #757 =
Transition Matrix: [[0.536

= EPOCH #780 =
Transition Matrix: [[0.53679055 0.46320945]
 [0.48260416 0.51739584]]
Initial Dice Probability: [0.64516324 0.35483676]
Emission Matrix: [[0.21014065 0.18707269 0.20299871 0.18045806 0.13242319 0.0869067 ]
 [0.18286912 0.21744615 0.17357552 0.21085991 0.11553563 0.09971368]]
Fitness: 0.49925704684134276

= EPOCH #781 =
Transition Matrix: [[0.53674448 0.46325552]
 [0.48253911 0.51746089]]
Initial Dice Probability: [0.67397522 0.32602478]
Emission Matrix: [[0.18339084 0.21610528 0.17491289 0.21081019 0.1150519  0.0997289 ]
 [0.21040336 0.18756014 0.20248704 0.17961916 0.13341413 0.08651617]]
Fitness: 0.5006412704429796

= EPOCH #782 =
Transition Matrix: [[0.53678895 0.46321105]
 [0.48256161 0.51743839]]
Initial Dice Probability: [0.64254245 0.35745755]
Emission Matrix: [[0.21035983 0.1880182  0.20117731 0.18090514 0.13334863 0.0861909 ]
 [0.18264516 0.21646809 0.1754573  0.21039614 0.11458208 0.10045123]]
Fitness: 0.49927704786262206

= EPOCH #783 =
Transition Matrix: [[0.

= EPOCH #806 =
Transition Matrix: [[0.53675063 0.46324937]
 [0.48186165 0.51813835]]
Initial Dice Probability: [0.6415803 0.3584197]
Emission Matrix: [[0.21034959 0.18798268 0.20122608 0.18091967 0.13328206 0.08623991]
 [0.18266967 0.21649037 0.17541998 0.2103663  0.11466015 0.10039353]]
Fitness: 0.49927399290583785

= EPOCH #807 =
Transition Matrix: [[0.53667153 0.46332847]
 [0.48175799 0.51824201]]
Initial Dice Probability: [0.67367375 0.32632625]
Emission Matrix: [[0.1822052  0.21659529 0.17599861 0.20923354 0.11547298 0.10049437]
 [0.21157847 0.18709935 0.20133611 0.18127783 0.1329568  0.08575145]]
Fitness: 0.5005597095502022

= EPOCH #808 =
Transition Matrix: [[0.53675952 0.46324048]
 [0.48181092 0.51818908]]
Initial Dice Probability: [0.64366165 0.35633835]
Emission Matrix: [[0.2116989  0.18656649 0.20136429 0.18178256 0.13219218 0.08639559]
 [0.18125298 0.21797683 0.17525539 0.20950031 0.11576971 0.10024479]]
Fitness: 0.49932214602767977

= EPOCH #809 =
Transition Matrix: [[0.53

= EPOCH #832 =
Transition Matrix: [[0.53673926 0.46326074]
 [0.48113274 0.51886726]]
Initial Dice Probability: [0.64244006 0.35755994]
Emission Matrix: [[0.21160345 0.186662   0.20135993 0.18174952 0.13222203 0.08640307]
 [0.1813677  0.21786152 0.17527384 0.20951958 0.11574769 0.10022967]]
Fitness: 0.4993166251446257

= EPOCH #833 =
Transition Matrix: [[0.53667344 0.46332656]
 [0.48103443 0.51896557]]
Initial Dice Probability: [0.67075118 0.32924882]
Emission Matrix: [[0.18248917 0.21783576 0.17469645 0.20933381 0.1159642  0.09968061]
 [0.21127964 0.18583848 0.20266127 0.18118313 0.13244927 0.08658821]]
Fitness: 0.5005796094588424

= EPOCH #834 =
Transition Matrix: [[0.53672628 0.46327372]
 [0.48105727 0.51894273]]
Initial Dice Probability: [0.64250496 0.35749504]
Emission Matrix: [[0.21022761 0.18708876 0.20275992 0.18066302 0.13239917 0.08686153]
 [0.18280844 0.21739744 0.1738526  0.21061664 0.11557824 0.09974664]]
Fitness: 0.4992586227586895

= EPOCH #835 =
Transition Matrix: [[0.53

= EPOCH #858 =
Transition Matrix: [[0.53672408 0.46327592]
 [0.48040012 0.51959988]]
Initial Dice Probability: [0.64128735 0.35871265]
Emission Matrix: [[0.21026165 0.18709766 0.2026672  0.18073806 0.13239265 0.08684278]
 [0.18278534 0.2173751  0.17396058 0.21052639 0.11559227 0.09976032]]
Fitness: 0.4992589173671703

= EPOCH #859 =
Transition Matrix: [[0.53667417 0.46332583]
 [0.48032945 0.51967055]]
Initial Dice Probability: [0.67006683 0.32993317]
Emission Matrix: [[0.18328745 0.21626998 0.17496681 0.21050557 0.11524601 0.09972419]
 [0.21046353 0.18743982 0.20238532 0.17998351 0.13318452 0.0865433 ]]
Fitness: 0.5006349601576013

= EPOCH #860 =
Transition Matrix: [[0.53672515 0.46327485]
 [0.48035719 0.51964281]]
Initial Dice Probability: [0.63927267 0.36072733]
Emission Matrix: [[0.2103384  0.18790555 0.2013216  0.18095342 0.13314997 0.08633106]
 [0.18270994 0.21654009 0.17534853 0.210301   0.11481537 0.10028507]]
Fitness: 0.4992679381607899

= EPOCH #861 =
Transition Matrix: [[0.53

= EPOCH #884 =
Transition Matrix: [[0.53673872 0.46326128]
 [0.47971708 0.52028292]]
Initial Dice Probability: [0.63819181 0.36180819]
Emission Matrix: [[0.21033782 0.18787268 0.20135849 0.18096831 0.1330985  0.0863642 ]
 [0.18272224 0.21656176 0.17532161 0.21027326 0.11487604 0.10024509]]
Fitness: 0.4992655623097245

= EPOCH #885 =
Transition Matrix: [[0.53666345 0.46333655]
 [0.47961776 0.52038224]]
Initial Dice Probability: [0.66965698 0.33034302]
Emission Matrix: [[0.18243657 0.21654475 0.17586046 0.2093337  0.11548481 0.10033971]
 [0.21130239 0.18719098 0.20144277 0.18121351 0.13292099 0.08592936]]
Fitness: 0.5005733803695765

= EPOCH #886 =
Transition Matrix: [[0.53675067 0.46324933]
 [0.47967206 0.52032794]]
Initial Dice Probability: [0.63963468 0.36036532]
Emission Matrix: [[0.21141636 0.18684079 0.20136123 0.18167966 0.13228152 0.08642044]
 [0.1815936  0.2176431  0.17530127 0.20956085 0.11570463 0.10019654]]
Fitness: 0.4993051867280067

= EPOCH #887 =
Transition Matrix: [[0.53

= EPOCH #910 =
Transition Matrix: [[0.53677916 0.46322084]
 [0.47904938 0.52095062]]
Initial Dice Probability: [0.63836603 0.36163397]
Emission Matrix: [[0.21134437 0.18690623 0.20136585 0.18165054 0.1323049  0.08642811]
 [0.18168104 0.21756195 0.17530824 0.20957826 0.11568804 0.10018247]]
Fitness: 0.4993005191971941

= EPOCH #911 =
Transition Matrix: [[0.53671165 0.46328835]
 [0.47895116 0.52104884]]
Initial Dice Probability: [0.66701413 0.33298587]
Emission Matrix: [[0.18254165 0.21756322 0.1749228  0.20933233 0.11590046 0.09973954]
 [0.21118585 0.18616128 0.20239124 0.18122398 0.13249127 0.08654638]]
Fitness: 0.5005844446605887

= EPOCH #912 =
Transition Matrix: [[0.53677266 0.46322734]
 [0.47898225 0.52101775]]
Initial Dice Probability: [0.6384809 0.3615191]
Emission Matrix: [[0.21032938 0.18711948 0.20248538 0.18087683 0.13238546 0.08680346]
 [0.18274067 0.21732525 0.17417335 0.21035686 0.11561488 0.099789  ]]
Fitness: 0.49925885620379457

= EPOCH #913 =
Transition Matrix: [[0.536

= EPOCH #936 =
Transition Matrix: [[0.53681629 0.46318371]
 [0.4783768  0.5216232 ]]
Initial Dice Probability: [0.63720823 0.36279177]
Emission Matrix: [[0.21035604 0.18712939 0.20241543 0.18092689 0.13238505 0.0867872 ]
 [0.18272361 0.21730379 0.17425572 0.21029447 0.11562156 0.09980085]]
Fitness: 0.4992585638710566

= EPOCH #937 =
Transition Matrix: [[0.53676262 0.46323738]
 [0.47830108 0.52169892]]
Initial Dice Probability: [0.66603921 0.33396079]
Emission Matrix: [[0.18319463 0.21639842 0.17502043 0.21027468 0.11537921 0.09973263]
 [0.21051955 0.18734982 0.20229157 0.18026254 0.13302307 0.08655345]]
Fitness: 0.5006294114124744

= EPOCH #938 =
Transition Matrix: [[0.53681992 0.46318008]
 [0.47833409 0.52166591]]
Initial Dice Probability: [0.6356562 0.3643438]
Emission Matrix: [[0.21034436 0.1878021  0.20143099 0.18100031 0.13299727 0.08642497]
 [0.18273973 0.21660903 0.17527004 0.21021474 0.11499589 0.10017057]]
Fitness: 0.4992608079283042

= EPOCH #939 =
Transition Matrix: [[0.5367

= EPOCH #962 =
Transition Matrix: [[0.5368769  0.4631231 ]
 [0.47774276 0.52225724]]
Initial Dice Probability: [0.63448936 0.36551064]
Emission Matrix: [[0.21035017 0.18777225 0.20145917 0.18101354 0.13295822 0.08644666]
 [0.18274368 0.2166293  0.17525053 0.2101907  0.11504239 0.1001434 ]]
Fitness: 0.4992589244189186

= EPOCH #963 =
Transition Matrix: [[0.53680391 0.46319609]
 [0.47764593 0.52235407]]
Initial Dice Probability: [0.66549656 0.33450344]
Emission Matrix: [[0.18258936 0.21653142 0.17574224 0.20941307 0.11550075 0.10022316]
 [0.21111287 0.18723901 0.20153317 0.18116567 0.13288429 0.086065  ]]
Fitness: 0.5005833747358609

= EPOCH #964 =
Transition Matrix: [[0.53689108 0.46310892]
 [0.47770168 0.52229832]]
Initial Dice Probability: [0.63547121 0.36452879]
Emission Matrix: [[0.21120461 0.18702697 0.20138321 0.18158904 0.13235161 0.08644456]
 [0.18185209 0.2174095  0.17531466 0.2096154  0.11565556 0.10015279]]
Fitness: 0.499290893036734

= EPOCH #965 =
Transition Matrix: [[0.536

= EPOCH #988 =
Transition Matrix: [[0.5369606  0.4630394 ]
 [0.47712449 0.52287551]]
Initial Dice Probability: [0.63416938 0.36583062]
Emission Matrix: [[0.21115144 0.18707034 0.20139343 0.18156339 0.13237006 0.08645135]
 [0.18191778 0.21735347 0.17531409 0.20963106 0.11564299 0.10014061]]
Fitness: 0.499286983493747

= EPOCH #989 =
Transition Matrix: [[0.53689159 0.46310841]
 [0.47702614 0.52297386]]
Initial Dice Probability: [0.66310049 0.33689951]
Emission Matrix: [[0.18258837 0.21735775 0.17507256 0.20935274 0.1158436  0.09978498]
 [0.21110442 0.18640757 0.20220631 0.18123644 0.13252953 0.08651573]]
Fitness: 0.5005884829660167

= EPOCH #990 =
Transition Matrix: [[0.53695955 0.46304045]
 [0.47706435 0.52293565]]
Initial Dice Probability: [0.63429878 0.36570122]
Emission Matrix: [[0.21040955 0.1871509  0.20227965 0.18101771 0.13238908 0.08675311]
 [0.18269029 0.21725825 0.1744168  0.21017853 0.11563049 0.09982564]]
Fitness: 0.49925745312526665

= EPOCH #991 =
Transition Matrix: [[0.53